### ISSUE TITLE
[FEATURE] Only destroy modules that have been explicitly been deprecated

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#196]
**Is your feature request related to a problem? Please describe.**
When working in a multi-developer environment, it is very simple to accidentally delete modules by running seedfarmer apply with different versions of a manifest. When this happens, it is extremely destructive and could cause cascading issues e.g. when modules fail to delete and enter CLOUDFORMATION DELETE_FAILED state, which stops all future updates to dependent modules.

Similarly, when developers move modules to different groups this causes the same destructive behaviour.

**Describe the solution you'd like**
Define a safer path for removing modules by only supporting  destruction of modules that have explicitly been `deprecated`. 

That means modules should:

- First modules should be set to `deprecated` and stages for deletion in the manifest and `seedfarmer apply` should be run (this only updates the metadata and does not destroy the module)
- Once a module has been deprecated and is then removed from the manifest it triggers the destroy in the deployspec

Considered cases:
- When a module is removed from a manifest which hasn't been deprecated, throw an exception on seedfarmer apply
- When a module is moved to a different group without being deprecate throw an exception on seedfarmer apply
- When a module is marked as deprecated, clearly show it in the `seedfarmer apply` tables

Implementing this would make using seedfarmer much safer for the large enterprise use cases it is intended for. 

**Describe alternatives you've considered**
We've implemented a CICD pipeline to stop this from happening, but still developers working on local manifest and running seedfarmer apply locally end up destroying modules unintentionally.

**Comment by zaremb** [comment]
+1 on this. 
Accidental delete happened with  module that everything else depends on. As this deletion failed (due to the fact that other modules use its resources) nothing can be deployed now without fixing the deletion. To fix deletion, we have to remove all other resources. 

Additionally, it would be great for CLI to ask for confirmation (skipped if `-y` argument is present). I.E 
`Do you want to perform these actions?` after `seedfarmer apply`. This will also prevent many accidental deletes, as you will first see  which modules will be added and which will be destroyed before proceeding.

**Comment by chamcca** [comment]
seedfarmer is not intended to support concurrent management of a single deployment. beyond the delete problem, you have all kinds of issues with conflicting stack updates, metadata management, and others. the intent is that a named deployment is only ever under change by a single process.

if working in an environment where multiple devs are sharing an account, it is recommended to dedicate a deployment to each developer. if they need to share a deployment.yaml file, then use of the `nameGenerator` on the manifest is recommended.

at best, seedfarmer might be updated to "lock" a deployment so that concurrent operations on a single deployment do not occur. but this is risky and poses other problems. i do not like the idea of dual phase deprecation/delete...

**Comment by a13zen** [comment]
I can appreciate that, however, users will use the tool however they see fit, and not as intended by us only. So we need to make it safer and more robust.

If an explicit two-step deletion process is not ideal, at the very least a deletion safeguard should be added, where `seedfarmer apply` does not delete modules scheduled for deletion unless a flag like `--destroy-removed-modules` is passed allong with it.

**Comment by chamcca** [comment]
so, default to `--dry-run`? the manifests declare/define the deployment. we cannot allow an `apply` that creates/updates modules but does not destroy deleted ones. doing so would create a discrepancy between the deployment declared by the manifests and the modules actually deployed. we could change default behavior of the CLI to execute a dry-run and report and only deploy if flagged.

**Comment by a13zen** [comment]
Defaulting to dry run would be another solution. So
- `seedfarmer apply` does a dry run and prompts if it should apply
- user enters `y` to accept, and it does the actual apply

- `seedfarmer apply --auto-approve` skips the dry run

**Comment by dgraeber** [comment]
I am evaluating using a dependency tree logic to stop the deletion of modules that are dependencies elsewhere in the deployment

**Comment by dgraeber** [comment]
Logic added to prevent deletion of modules that have dependencies
