### ISSUE TITLE
[FEATURE] Provide more details on the changes that would be applied to the environment upon deployment

### ISSUE THREAD

**Issue by capblucz** [awslabs/seed-farmer#480]
**Is your feature request related to a problem? Please describe.**
Upon executing `seedfarmer apply ... --dry-run` I am now presented with information on which modules have been changed, which will be removed etc. There is, however no detailed information regarding the kind of changes made to the modules and what will be deployed in reality to the environment, just a blackbox stating that "module has been updated".

**Describe the solution you'd like**
I would like to have an additional option in the CLI for `seedfarmer apply ... --dry-run` (ex. --diff) that would print out all the detailed changes that are about to be applied to the environment. 

**Describe alternatives you've considered**
A cumbersome way to achieve this would be to go to the each individual module in the deployment and depending on the tool used in the module call ex. `terraform plan ...` or `cdk diff` and provide it with all the required environment variables manually to verify the output

**Additional context**

**Comment by dgraeber** [comment]
@capblucz Thanks for your request.  Unfortunately, we will not be able to support his request.  SeedFarmer detects changes to the code or to the manifests to determine if changes need to be applied.  Since SeedFarmer supports multiple means of deployment (CDK, CFN, Terraform, etc) , cannot determine the actual change set across all these technologies without actually executing the deploy with the framework specified as specified in the deployspec.

Due to this agnostic support, we cannot determine the actual changesets in the `--dry-run`.

**Comment by dgraeber** [comment]
No need for apologies....this is how we synthesize ideas.  Your request is not the first (have a detailed exec plan).  There are a few blockers: 1\ not all tooling can support an execution change set -- terraform and cdk can, but we have no guarantee that other modules will 2\ it takes 2 minutes to provision and install the deployspec....it will be a bad user experience to sit and wait for that (x the number of groups) just to see the explain plan 3\ we do not want to interject logic into the actual modules related to the state of the deploy (dry-run or not)....that is solely the responsibility of seedfarmer.

We are going to explore how to accommodate this (perhaps look at a docker image that can run locally but has the inability to deploy anything??). 

Please feel free to keep posing questions / features / etc.   It really facilitates the direction we go in with SeedFarmer and modules.
