### ISSUE TITLE
[FEATURE] Improved logging of credential / authentication issues for cross-account profiles

### ISSUE THREAD

**Issue by 3sztof** [awslabs/seed-farmer#528]
## Issue description

In the current implementation, Seedfarmer's error messages are extremely unhelpful if a module has to be pulled (for example) from a CodeCommit remote in a different account, using a cross-account profile.

In my case, the issue was trivial, I haven't used a proper set of credentials in my shell, so the cross-account profile couldn't be assumed properly. Seedfarmer produced a cryptic stack trace, that looked like an internal tool error and ended with:
`git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)`.

As you can see, the issue is not very explicit.

## Solution proposal

When using any external embedded functionality (such as git commands) that could have their own dependencies and throw their own exceptions, Seedfarmer could catch the most common issues (such as expired / wrong credentials) and wrap the embedded functionalities exceptions with more explicit prompts for the user (in my case a prompt like "access denied / wrong or expired credentials" would save me a lot of time and frustration).

To keep it positive:
Thank you for the awesome tool, this is just an enhancement idea! :)

**Comment by dgraeber** [comment]
I get the request.  Right now, git returns status codes (like status 1)....which is not really helpful at all.  I have no idea if the issue is expired credentials or if wrong credentials or if the repo doesn't exist.  I have 2 choices: return what SF gets or mask that response with a generic message....neither of which sounds ideal...

I am looking at revamping the messaging to give hints...but the ask to provide a reason for failure is limited to what SF gets from the supporting systems...

But I get it...this is a valid ask.

**Comment by dgraeber** [comment]
I added some hints when an error occurs and the error messages returned.  I delved into the exit codes (ex 1 and 128) but could not find consistent messaging for each status code, so I am just echoing it back.
