### ISSUE TITLE
[FEATURE] Unified Destroy

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#545]
**Is your feature request related to a problem? Please describe.**
As discussed in #529. Currently users experience issues when trying to delete modules that are referenced locally. This is primarily caused because of the disconnect between the stored manifest in SSM and the local code being used for deletion. 

If a customer has deployed a module, then modified the local module code (in particular adding a new parameter), and then try to destroy the already deployed module (without deploying the changed code), the module deletion would fail.

This is a very common occurrence when working on large teams, where multiple people would be changing module code and each person on the team might be using their own namespace with older modules deployed. 

**Describe the solution you'd like**
Store the code for modules that are deployed. Use the stored code to delete the module instead of the local code. Allow users to force update the stored code. 

**Describe alternatives you've considered**
Workarounds described in #529.

**Comment by dgraeber** [comment]
This will require a major change to how we persist information (SF will need S3-backed storage and indexing), which then implies role policy changes....essentially, this would be a breaking release and major update to the codebase.

I would then consider only using persisted code (if local) or commithash (if using https://github.com/awslabs/seed-farmer/pull/537 work) to always destroy.  Unfortunately, this complete removes the ability to do iterative development when destroying as the deployspec can never be overridden w/o deploying first....

Thoughts?

**Comment by TUMAAA** [comment]
I am thinking whether Seedfarmer should at least persist the git commit hash and any diff as patch in the SSM. This way it is possible for seedfarmer to detect that it wont be able to take down a deployment and propose to checkout an older commit and apply a specific patch to be able to delete a deployment first before redeploying from scratch.

**Comment by dgraeber** [comment]
@TUMAAA With the latest release, if the module is sourced from a git-compliant repo, we now store the commithash of a successfully deployment module in SSM (in both the module metadata and the module manifest).  An end user can fetch the commithash of the deployed module via `seedfarmer list moduledata`.  But, SF will not have the logic to determine if a module can be destroyed (it is oblivious to the actual module code itself).  The additional logic you proposed (apply a specific patch) is not something we can support, but are looking at possibly just always using the code behind a commithash as the source on destroy....and weighing the ramifications.

**Comment by DrWorkhard** [comment]
Beginner question:
If I understand correctly, this issue is caused by the destroy being executed by cdk. It occurs because the infrastructure which is deployed and which is in local code differ.

So actually the error is caused by cdk which cannot connect the dots anymore because they are out of sync. However, for deletion in all of my cases I actually just need the names of the stacks which were deployed.

So could the solution in cases where a module "owns" one or more stacks be: 
1. in my own code: determine the names of the stacks to be deployed
2. in my deployspec destroy: just do cloudformation delete stack with the names from 1.

**Comment by dgraeber** [comment]
@DrWorkhard Thanks for your comments!  Let me elaborate on the issue that is being discussed.  
SF deploys code (modules) by leveraging a deployspec.  The deployspec is responsible for calling the actual deployment API (CDK, CFN via API, Terraform, bash, etc) as well as calling other things (ex. calling CDK and then making AWS CLI calls to stage data).  The deployspec is wrapped in the module code, as per the SF spec.  A module can be deployed 1..n times as long as the logical name is different (same code, different name) in a deployment.

There are two specific use cases this FR tries to address:
1. deploying code from local filesystem (clone a repo and refer to local paths in manifests)
2. deploying code from git (SF takes care of cloning and distributing code).

For now, lets take use case 1 (local code).  A user refers to a local filepath in a manifest and deploys (great!).  Then, they either change the module code (cdk code for example) or the deployspec on the local filesystem (or moves the  code to a different relative path altogether) and then tries to DESTROY without redeploying.   Now the code, relative paths and potentially the deployspec can be different than what the deployed module needs in order to be destroyed.  We have put in place the ability to update deployspecs, but if you move or modify other parts of the module code locally, that will not be reflected in the deployment and the module will potentially fail to destroy due to being out of sync.   So in your response, it really is not simply doing a CFN stack delete (and PLEASE if you are deploying via CDK, destroy via CDK ... this is a general statement).  The bigger issue is that SF does not have an identical replica of the code persisted in order to destroy.  The manifests persisted refer to the same relative path used to deploy, and if that code is altered locally or moved altogether, the ability to destroy is impaired. 

In use case 2 - this is really a matter of proper repo management.  If a user is referencing a main branch, and main is the default for all PR's, then there is a strong chance that the underlying code on that branch has changed.  We STRONGLY encourage users to reference release branches (that way the code is static).  BUT...the SF api should not (IMO) try and compensate for software practices: if you want to reference a main branch that sustains changes, you can...but that is not up to SF to manage.  But, we are not persisting the commit hash just in case, for reference. 

I hope this helps elaborate.  If you'd like we can have a deeper dive conversation.

**Comment by a13zen** [comment]
+1 Use case where Unified Destroy (using stored module code for destruction) would help is to allow users to delete modules both from the manifest + locally from the modules folder within a single commit and run the destruction with `seedfarmer apply`. Right now, to remove a module that is referenced locally requires 2 commits essentially (when `seedfarmer apply` is run via CI/CD pipelines). The first commit to remove the module refernce from the manifest. The second one to delete the actual code in the repository.

**Comment by dgraeber** [comment]
@a13zen thanks for the feedback.  We are actively working on it

**Comment by vkresch** [comment]
Just wanted to check if this issue is resolved or still work in progress? I am using seed farmer 4.0.2 and whenever I delete a pipeline from the manifest file I need to keep the module directory/path and all the related environmental variables to destroy it (redeployment). Only when it is destroyed I can remove the module directory. Would it be possible to remove the pipeline in the manifest and the directory in one commit and only deploy once which triggers a destroy for the deleted pipeline? Thanks!

**Comment by dgraeber** [comment]
This is implemented in 4.0.1.  If the module was deployed / redeployed with this version then SF should be leveraging the persisted bundle when destroying.  I will validate your use case to confirm.

**Comment by dgraeber** [comment]
@vkresch Please install 4.0.3 and you should be good

`pip install --upgrade seed-farmer==4.0.3`
