### ISSUE TITLE
[FEATURE] Identify module deployed by each build on CodeBuild build history page 

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#56]
**Is your feature request related to a problem? Please describe.**
In CodeBuild you can't see which module is currently being deployed by which build run directly. You need to go into the build and check the Environment variables for the MODULE_NAME. This is a problem when seed-farmer is deploying many modules in parallel.

**Describe the solution you'd like**
Although it is not possible to specify unique build IDs. We can still get the contextual information by:
- Adding an identifier to s3 file location either in s3npath or zip file name identifying `deployment-group-module`. The s3 key is displayed in the source version column
- Alternative: Adding identifier as Source Version Override (if this is even possible with s3 source needs to be investigated)

**Comment by dgraeber** [comment]
We will look into this - it may need support from codeseeder also.

**Comment by dgraeber** [comment]
@chamcca Lets circle back on this?

**Comment by dgraeber** [comment]
@a13zen We have decided to move forward with the following:
we will add the <group.name>-<module.name> to the directory structure of the bundle so that the console will will give indication under the `Source version` category.   For example, the existing builds have (as a `Source version`) the reference `[codeseeder-addf-616260033377-alsjro/codeseeder/vhgmqpfb/bundle.zip` will become `[codeseeder-addf-616260033377-alsjro/codeseeder/vhgmqpfb/core-eks/bundle.zip`

**Comment by a13zen** [comment]
@dgraeber, this is going to be an extremely useful change. Thanks!
