### ISSUE TITLE
[QUESTION] Best method of updating CodeBuild Project / CodeSeeder Seedkit

### ISSUE THREAD

**Issue by chamcca** [awslabs/seed-farmer#564]
As the title says, looking for info on the best or recommended method of updating the CodeBuild Project used by an existing environment. We have a number of environments deployed, some for individual developers, some for dev, test, environments, some for production environments.

The Seedkit CFN stacks for these environments were originally deployed by the 2.x version of SeedFarmer (and associated CodeSeeder), as such, the CodeBuild image they are using is outdated (think NodeJS 16.x, Python 3.8). We are currently running seed-farmer-3.2.2 and aws-codeseeder-0.11.1. Manually executing `codeseeder deploy seedkit` does not force an update of the CFN stack or the CodeBuild Project, and a `seedfarmer apply` is happy to use the existing CodeBuild Project. What is the recommended process for updating these *without* having to remove the environment or manually delete the CFN stacks/seedkits? Any recommendations are appreciated.

**Comment by dgraeber** [comment]
We have added a flag to the seedfarmer apply called `--update-seedkit`.  This is by default turned off, but if passed in it will take the latest template from codeseeder and apply it.  This was implemented due to distributed seedfarmer commands always updating the seedkit, causing thrash and inconsistencies when multiple users using different SF versions collide on a single deployment.  This was also implemented to support our future upgrade to `aws/codebuild/standard:7.0` (not enacted yet).  

REF: https://seed-farmer.readthedocs.io/en/latest/cli_commands.html#summary-of-commands

NOTE: if you are stuck, let me know. I can patch a release of codeseeder with `aws/codebuild/standard:7.0` as the default PDQ

**Comment by dgraeber** [comment]
Also....we do support overriding the codebuild image with an aws-curated image (such as `aws/codebuild/standard:7.0`) at the account, region, and module levels...in case you cannot wait for an update to the default AWS-CodeSeeder image

https://seed-farmer.readthedocs.io/en/latest/manifests.html#deployment-manifest

**Comment by dgraeber** [comment]
@chamcca  I have released codeseeder with a patch that updates the default codebuild version to `aws/codebuild/standard:7.0`) .  It is in aws-codeseeder 0.12.1

You can:
1. update your aws-codeseeder versiont to 0.12.1
2. either:
  - run `codeseeder deploy seedkit <project>`
  - run  `seedfarmer apply <manifests> --update-seedkit`
  
Ping if this does move you forward.

**Comment by chamcca** [comment]
perfect. much appreciated. our outdated CodeBuild images were on the verge of being a problem, and i _really_ didn't want to have to tear down the seedkit stacks to update them.
