### ISSUE TITLE
[BUG] MD5 hash includes all files resulting in diff check missmatch

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#58]
**Describe the bug**
The current MD5 calculation includes all files in a module folder. This means if hidden files such as .env or git ignored folders such as virtual environments or cdk.out have changes in them when two people are on the same git branch with no changes, two different MD5 hashes are calculated. 

**To Reproduce**
1. Add git ignored files to a module
2. `seedfarmer apply --dry-run`
3. Change is detected. It will not be detected for another user

**Expected behavior**
Files in the .gitignore should be excluded from the MD5 hash to enable true gitops compatibility. If Git detects a change, seedfarmer should detect it. If git does not, seedfarmer should not.

**Comment by dgraeber** [comment]
I currently have a WIP that ignores the following files in the module when determining changes:
`README.md
modulestack.template
setup.cfg
requirements-dev.txt
requirements-dev.in`

As far as the .gitignore requests, I assume that applies to only a .gitignore located in the module relative path...correct @a13zen ?

**Comment by a13zen** [comment]
Git checks a .gitignore file first in the local folder and then any parent folder. https://git-scm.com/docs/gitignore

We could use the same mechanism. The idea is that if customers use a gitops model of deployment, things not in git shouldn't contribute to the hash. So using .gitignore is a natural mechanism for this.

**Comment by dgraeber** [comment]
@a13zen Agreed and exploring.  I think that we will have to limit the top folder to be at the module root (ex `modules/<group>/modulename/.gitignore`) as that is the top dir that is evaluated.  As far as subdirs with the module directories, I will have to investigate.  Unfortunately, we have an issue with the checksum that is created (not respecting nested dirs and ignoring of files in subdirs by relative path) so that is the issue i am wrangling....
Ping me and we can discuss details if interested....
