### ISSUE TITLE
[FEATURE]Deploy modules from a AWS Region to a AWS LocalZones

### ISSUE THREAD

**Issue by JunjieTang-D1** [awslabs/seed-farmer#606]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to deploy a piece of CDK code e.g. EKS cluster to the Hamburg LocalZone, from the AWS Frankfurt region.

**Describe the solution you'd like**
Here is the architecture of seed-farmer and code-seed. The step 2 to 6 will run in the Frankfurt region. Only the deployment target in step 7 e.g. CDK for EKS clusters is the Hamburg LocalZone

![image](https://github.com/awslabs/seed-farmer/assets/87007858/56d65952-f6ae-4c6c-a04a-2a9cabe927b1)

**Describe alternatives you've considered**
There is no alternative solution to make a consistent developer experience.

**Comment by dgraeber** [comment]
We will take a look and evaluate LOE

**Comment by dgraeber** [comment]
@JunjieTang-D1 
It appears that once the VPC in the region is configured to support a LocalZone, you just reference the subnet and all still works (EKS itself would probably need a self-managed node group in order to leverage the LZ, but that is not SF's concern).  

I don't understand this comment, though:
`I'm always frustrated when I have to deploy a piece of CDK code e.g. EKS cluster to the Hamburg LocalZone, from the AWS Frankfurt region.`

I am not sure I understand this as the LZ must be associated with a VPC in a region.  Though I understand your use case, I am not understanding your request.  The LZ cannot exist without the region, so CDK code must be deployed int he region.

Please contact me
